### ISSUE TITLE
Census FTP doesn't seem to exist anymore

### ISSUE THREAD

**Issue by darylknight** [aaronpdennis/congress-maps#11]
Although their website still says there's an FTP server, I'm not able to connect to it in any way. The wget command in the docs returns:

`unable to resolve host address ‘ftp2.census.gov’`

I'm also getting no response using Transmit.

**Comment by jq-87** [comment]
Downloads are here: https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html

**Comment by darylknight** [comment]
Hey - appreciate the response!
Honestly though this was 2 years ago and I have no idea what project I was looking at it for, but will close the issue.
