### ISSUE TITLE
One mbtiles source, without dropping label points

### ISSUE THREAD

**Issue by aaronpdennis** [aaronpdennis/congress-maps#4]
Using the [tippecanoe geojson extension](https://github.com/mapbox/tippecanoe#geojson-extension) might force inclusion of label points at all zoom levels. This would require a small change to `process.js`.

Addresses problems raised in #2 @JoshData

**Comment by JoshData** [comment]
What does tippecanoe do if we don't specify?

**Comment by aaronpdennis** [comment]
Without specifying, Tippecanoe will simplify geometries at lower zoom levels by arbitrarily dropping vertices. This could mean the point feature gets dropped. In our case, label points were usually dropped somewhere in the creation of simplified, zoomed out geometries for congressional districts, and aren't included until higher zoom levels where there is no simplification occurring.

**Comment by JoshData** [comment]
Ahhh. Another idea would be to generate two vector tiles files and then merge them, although I can't see an easy way to do that.

**Comment by aaronpdennis** [comment]
Yeah, seems like there should be a way to merge two layers from different mbtiles into one file, but not sure how... I'm going to try the Tippecanoe extension approach and see if that will work.

**Comment by aaronpdennis** [comment]
Actually, tippecanoe had a --base-zoom option that I missed. This shouldn't be any problem to include labels and districts in the same tile source.

**Comment by aaronpdennis** [comment]
@JoshData see #5
