### ISSUE TITLE
upload issue

### ISSUE THREAD

**Issue by AllanMarcus** [aaronpdennis/congress-maps#6]
computer:congress-maps 114282$ node upload.js data/cd-114-2015.mbtiles
staging data/cd-114-2015.mbtiles > undefined.cd-114-2015 ...
(node:49090) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): TypeError: Cannot read property 'accessKeyId' of undefined
(node:49090) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Hi. I get all the way to the node upload.js and then I get this failure. Any ideas?

**Comment by aaronpdennis** [comment]
first thought is the `MAPBOX_WRITE_SCOPE_ACCESS_TOKEN` environment variable isn't defined with a write access token?

other possibility is changes to the Mapbox client API are causing the error. the package used originally was perhaps a beta version

**Comment by AllanMarcus** [comment]
I created a token as shown in the attached image. Did I choose the wrong scopes?

![write](https://cloud.githubusercontent.com/assets/505572/22599558/964a6aca-e9f4-11e6-8fcf-3381b77e0b23.png)

**Comment by aaronpdennis** [comment]
looks right. did you run the `export MAPBOX_WRITE_SCOPE_ACCESS_TOKEN=<your mapbox write scope access token>` command?

**Comment by AllanMarcus** [comment]
yep

$ env | grep MAPBOX
MAPBOX_WRITE_SCOPE_ACCESS_TOKEN=xxx-replaced
MAPBOX_DEFAULT_ACCESS_TOKEN=xxx-replaced
MAPBOX_USERNAME=allanmarcus

**Comment by AllanMarcus** [comment]
More info

  client.createUploadCredentials(function(err, credentials) {
    console.log(err, 'staging', file, '>', id, '...');

here's "err"

{ Error: connect ECONNREFUSED 54.230.143.22:443
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '54.230.143.22',
  port: 443 }

**Comment by AllanMarcus** [comment]
This might be a corporate proxy issue, even though all my proxy settings are correct. I'm connected to a different network now (iPhone tethered :-) and the upload appears to be working.

Assuming I get this to work with the 114th congress, I will try with the 115th. All the files are there, so I hope all I have to do is change file names in the .js files.

**Comment by aaronpdennis** [comment]
awesome to hear! sorry I couldn't recognize the issue. let me know how it all works out.

**Comment by aaronpdennis** [comment]
@AllanMarcus is this error resolved?

**Comment by AllanMarcus** [comment]
yep, it was a corporate proxy issue. Something in the scripts does't work right with a proxy, but it worked well from home with no proxy.
